add org.apache.poi:ooxml-schemas:1.3 to fix poi3.14 error:
Caused by: java.lang.NoClassDefFoundError: org/openxmlformats/schemas/wordprocessingml/x2006/main/impl/CTRImpl$1TList
	at org.openxmlformats.schemas.wordprocessingml.x2006.main.impl.CTRImpl.getTList(Unknown Source)
	at cn.bc.template.util.DocxUtils.formatParagraph(DocxUtils.java:228)
	at cn.bc.template.util.DocxUtils.format(DocxUtils.java:159)
	at cn.bc.template.util.DocxUtils.format(DocxUtils.java:107)
	at cn.bc.template.domain.Template.format2Attach(Template.java:360)